import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { setupAudio, playSound, stopBackground, startBackground } from './modules/audio.js';
import { setupWorld } from './modules/world_map.js';
import { setupPlayer } from './modules/player.js';
import { setupUI, renderPlayerList, updateUIElementPositions, renderHealthBar } from './modules/ui.js';
import { setupGame } from './modules/game.js';
import PlayerModule from './modules/PlayerModule.js';
import { backpack, ITEM_DATA } from './modules/backpack.js';
import Global from './modules/Global.js';
import { registerStencilHelper } from './modules/stencil_shadows_adapter.js';
import { appendChatMessage } from './modules/safechat.js';
